-- login.sql
SET LINESIZE 200
SET PAGESIZE 100
SET TRIMSPOOL ON
SET TRIMOUT ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON
SET ECHO OFF
SET VERIFY OFF

-- Column formats
COLUMN object_name FORMAT A30
COLUMN object_type FORMAT A15
COLUMN employee_id FORMAT 99999
COLUMN first_name FORMAT A15
COLUMN last_name FORMAT A15
COLUMN email FORMAT A25
COLUMN hire_date FORMAT A12
COLUMN salary FORMAT 99999
COLUMN department_id FORMAT 9999
COLUMN department_name FORMAT A20
COLUMN name FORMAT A25
COLUMN department FORMAT A20
COLUMN annual_salary FORMAT 999999
COLUMN salary_rank FORMAT 9999
COLUMN row_num FORMAT 9999
COLUMN grade_level FORMAT A12